platform :ios, '15.0'

target 'MayaMind' do
  use_frameworks!

  # MediaPipe Pose Landmarker
  pod 'MediaPipeTasksVision', '~> 0.10.14'

  # Note: Supabase is added via Swift Package Manager (SPM), not CocoaPods
  # Add in Xcode: File > Add Package Dependencies > https://github.com/supabase/supabase-swift
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
